### PR TITLE
Use Sentry SDK v3

### PR DESCRIPTION
**Pull request by richardhj**
I made all necessary changes to address the latest updates in sentry/sentry and sentry/symfony.

### CODE REVIEW

**Comment by bytehead** [comment]
Can you allow edits from maintainers?

**Comment by richardhj** [comment]
This is already the case :)

**Comment by bytehead** [comment]
strange, can't push to your branch ... 🤔

**Review by bytehead — APPROVED** [review]

**Comment by bytehead** [comment]
`2.0.0` is released! Thank you very much! 🎉

**Pull request merged**
